### ISSUE TITLE
safe-cfn-custom-resource

### ISSUE THREAD

**Issue by odedniv** [zippadd/cfn-custom-resource#21]
Hey, I created a simple wrapper around your great library that allows safely handling CFN events: https://www.npmjs.com/package/safe-cfn-custom-resource
All the times your resource freezes (because of no reply) will no longer happen when using this library, even if some initialization failed (e.g. bad `require`).

What do you think about recommending it's usage here? I personally had a ton of problems developing custom resources until I decided to create this library, and I think it will be useful for this library's userbase.

**Comment by zippadd** [comment]
Hello - thank you for the kind words. Looks nice! I haven't seen references between modules too much on NPM (aside from the built in dependencies/dependents). What would you propose? A section in the README?

**Comment by odedniv** [comment]
That's what I thought

**Comment by zippadd** [comment]
My concern at this point is how I could be fair if others build on the library in the future. Should they get a recommendation if asked too? Does everyone get one and if so doesn't that render it moot?

As I said, I think your library looks great and I'm flattered that you would base it on this library. After some reflection though, it seems a recommendation for it fits better on a personal page or a blog post rather than the README of a open source library. People can find it as a dependent on NPM, so it's at least discoverable in a way that's equally fair to all who would build upon it.

If you do find some example libraries that recommend/link to others that build upon them in some manner, I'd be happy to review how they go about that and reconsider.

Another potential option would be to explore collaboration on the library of some sort offline. Let me know if you're interested and we can get a Slack or something rolling.

**Comment by odedniv** [comment]
Makes sense :+1:
